# Capgemini Written Test

In [1]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

### 1. What is the o/p of the below script

In [2]:
def list_comp():
    x = [1, 2, 3]
    [x.append(i) for i in range(3)]
    return x

print(list_comp())

[1, 2, 3, 0, 1, 2]


### 2. What will be the o/p of the below script

In [3]:
def outer_fn():
    x = 10
    def in_fn():
        nonlocal x
        x = 28
    in_fn()
    return x
print(outer_fn())

28


### 3. What will be the o/p of below script

In [4]:
try:
    result = 1 / 0
except (ZeroDivisionError, ValueError) as e:
    print(f"Eca exc: {e}")
except Exception as e:
    print(f"RRRR : {e}")
    

Eca exc: division by zero


### 4. For below script

In [7]:
import pandas as pd

data = {"Name" : ["Rama", "Sita", "Laxmana"],
        "Age" : [25, 35, 45],
        "City" : ["LKV", "SHM", "BDT"]}

df = pd.DataFrame(data)
df

Name  Age City
0     Rama   25  LKV
1     Sita   35  SHM
2  Laxmana   45  BDT

##### a. Add new column 'Salary' with default value 50000

In [8]:
df["Salary"] = 10000
df

Name  Age City  Salary
0     Rama   25  LKV   10000
1     Sita   35  SHM   10000
2  Laxmana   45  BDT   10000

##### b. Change the 'Age' of 'Sita' to 32

In [10]:
df["Age"].mask(df["Name"] == "Sita", 32, inplace=True)
df

Name  Age City  Salary
0     Rama   25  LKV   10000
1     Sita   32  SHM   10000
2  Laxmana   45  BDT   10000

In [11]:
df.loc[df["Name"] == "Sita", "Age"] = 35
df

Name  Age City  Salary
0     Rama   25  LKV   10000
1     Sita   35  SHM   10000
2  Laxmana   45  BDT   10000

##### c. Remove the 'City' column

In [12]:
df.drop(["City"], axis=1, inplace=True)
df

Name  Age  Salary
0     Rama   25   10000
1     Sita   35   10000
2  Laxmana   45   10000

### 5. For below script

In [14]:
import pandas as pd
import numpy as np

df = pd.DataFrame({"A" : [1,2,np.nan, 4], 
                   "B" : [np.nan, 2, 3, 4],
                   "C" : [1, np.nan, np.nan, 4]})
df

A    B    C
0  1.0  NaN  1.0
1  2.0  2.0  NaN
2  NaN  3.0  NaN
3  4.0  4.0  4.0

##### a. Fill missing values in column 'A' with mean of 'A'

In [15]:

df["A"].fillna(df1["A"].mean(), inplace=True)
df

A    B    C
0  1.000000  NaN  1.0
1  2.000000  2.0  NaN
2  2.333333  3.0  NaN
3  4.000000  4.0  4.0

##### b.Drop any rows where any value is missing

In [16]:
df.dropna(inplace=True)
df

A    B    C
3  4.0  4.0  4.0

### 6. For below script

In [17]:
df = pd.DataFrame({'Category' : ['A', 'A', 'B', 'B', 'C', 'C'],
                   'Value' : [10, 20, 30, 40, 50, 60]})

##### a. Group the DataFrame by 'Category' and calculate the sum of 'Value' for each category

In [20]:
df1 = df.groupby(['Category']).agg({'Value': 'sum'})
df1

Value
Category       
A            30
B            70
C           110

##### b. Calculate the mean of 'Value' for each category

In [22]:
df1 = df.groupby(['Category']).agg({'Value': 'mean'})
df1

Value
Category       
A          15.0
B          35.0
C          55.0

### 7. For below script

In [23]:
df1 = pd.DataFrame({'ID' : [1, 2, 3],
                    'Name' : ['Rama', 'Sita', 'Laxmana']})

df2 = pd.DataFrame({'ID' : [2, 3, 4],
                    'Score' : [85, 90, 95]})

##### a. Merge  df1 & df2 on the 'ID' column using outer join

In [26]:
df = df1.merge(df2, how='outer', on='ID')
df

ID     Name  Score
0   1     Rama    NaN
1   2     Sita   85.0
2   3  Laxmana   90.0
3   4      NaN   95.0

### 8. Split 'Name' column into columns 'First_Name' and 'Last_Name' 

In [37]:
df = pd.DataFrame({'Name' : ['Rama Chandra', 'Sita Devi', 'Laxmana Swamy']})
df

Name
0   Rama Chandra
1      Sita Devi
2  Laxmana Swamy

In [38]:
df1 = pd.DataFrame(df['Name'].str.split(' ').tolist(),
                                 columns = ['First_Name','Last_name'])
df1

First_Name Last_name
0       Rama   Chandra
1       Sita      Devi
2    Laxmana     Swamy

### 9. What is the o/p of below script

In [39]:
array = np.arange(1, 13)
reshaped_array = array.reshape(3, 4)
second_row = reshaped_array[1]
print("Resaped array:\n", reshaped_array)
print("Second row:\n", second_row)

Resaped array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Second row:
 [5 6 7 8]


### 10. What is the o/p of below script

In [40]:
array = np.zeros((3,3))
addition = np.array([1, 2, 3])
result = array + addition 
print("Resulting array:\n", result)

Resulting array:
 [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
